version: "3.7"
services:
  server:
    build:
      context: "."
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@database:5432/spotify-playlists?schema=public"
      DB_NAME: "spotify-playlists"
    ports:
      - 9999:80
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
    networks:
      - test_vm
    depends_on:
      - database

  database:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB=spotify-playlists
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - database:/var/lib/postgres
    expose:
      - 5433
    ports:
      - 5433:5432
    networks:
      - test_vm

volumes:
  database:

networks:
  test_vm:
